<?php
    $awards = array(
        array('id'=>'zoinno',
              'name'=>'조공 상',
              'who'=>'김탕',
              'permalink'=> 'https://www.facebook.com/zoinno',
              'thumbnail'=>'https://graph.facebook.com/zoinno/picture',
              'description'=>'"아마도"를 이용하기 위해서는 "선물"을 주셔야 하니 참 많은 선물들을 받았는데요. 이 분께 특히 이 상을 드리고 싶었어요. 작은 정수기 물통, 어두운 문 앞을 밝혀주는 센서등, 수생 식물을 꽂아 키울 수 있는 도구, 신디사이저등을 선물해주셨죠. 특히 센서등은 지금까지 가장 필요했던, 그리고 유용한 선물로 뽑고 싶어요 :)'),        
              
      array('id'=>'nazzaang',
              'name'=>'단골 상',
              'who'=>'하나짱',
              'permalink'=> 'https://www.facebook.com/nazzaang',
              'thumbnail'=>'https://graph.facebook.com/nazzaang/picture',
              'description'=>'조금 오랜 인연이 있었지만 그보다는 "아마도"때문에, 그리고 "아마도"를 찾아오시는  또다른 단골분들때문에 친해진 손님이에요. 또다른 단골분들과 함께오는 것은 물론이고, 바느질 모임을 주도하시기도 하고, 같이 반찬 모임을 진행하기도 했어요. 또 공연도 자주 보러 오셨네요. 멀다면 먼걸음 자주와주셔서 고마워요. 앞으로도 자주 오셔서 내년 "단골 상"도 거머쥐시길 바래요 :)'),
                             
      array('id'=>'geenie3',
              'name'=>'첫 고백 상',
              'who'=>'한바다',
              'permalink'=> 'https://www.facebook.com/geenie3',
              'thumbnail'=>'https://graph.facebook.com/geenie3/picture',
              'description'=>'처음으로 "아마도" 페이스북을 좋아한다고 고백해주셨어요. 물론 주인장인 저를 제외하고요. 고백을 받아들이진 못했지만 오래 오래 기억될거에요.'),
                            
      array('id'=>'twodahn',
              'name'=>'브로커 리 상',
              'who'=>'이지연',
              'permalink'=> 'https://www.facebook.com/twodahn',
              'thumbnail'=>'https://graph.facebook.com/twodahn/picture',
              'description'=>'지금은 꽤 많은 공연을 진행했지만 한때 "아마도"의 꿈만 같았던 하우스 콘서트의 부흥을 도운 당사자에게 이 상을 주고 싶었어요. 이 분은 가수 "시와"님과 연결해주셨고 좋은 공연으로 이어지게 해주셨어요. 계속 좋은 공연을 연결해주시는 제 2의 제 3의 브로커 X가 생기길 바라는 점에서도 이 상을 만들었어요. :)'),
                           
      array('id'=>'moderntrust',
              'name'=>'무조건 좋아 상',
              'who'=>'최호진',
              'permalink'=> 'https://www.facebook.com/moderntrust',
              'thumbnail'=>'https://graph.facebook.com/moderntrust/picture',
              'description'=>'"아마도"공간이 있는 성북동에 가까운 곳에서 근무를 하시며 여러 방면으로 도움을 주셨던 분이에요. 가장 인상 깊었던 것은 거의 모든 페이스북의 포스트에 "좋아요"를 눌러주셨어요. 어렵지 않은 작은 행동이지만 페이스북을 운영했던 초중기 때부터 큰 힘이 되는 작은 "피드백"이었어요. 고마워요 :)'),
                            
      array('id'=>'100000958806207',
              'name'=>'뜬금없 상',
              'who'=>'걍산',
              'permalink'=> 'https://www.facebook.com/100000958806207',
              'thumbnail'=>'https://graph.facebook.com/100000958806207/picture',
              'description'=>'이 분에겐 예약이란 따로 없으며, "아마도"는 그냥 놀러오면 되는 곳이라 생각하시는 분이세요. 뭔가 비꼬는 말투로 소개했지만 심심할만할때마다 찾아와 주셨으니.. 고마움은 다른이들에게 밀리지 않아요. 항상 스스로 자랑하시는 "아마도"에 가장 무거운 선물인 "다듬이돌"을 주신것에 스스로 대견해(?) 계세요. 가족 모르게 "아마도"에 선물을 주셨다가 "아내"분이 놀라셨던 적도 있는 분이시네요. 하하. 어쨋든 진심으로 감사드려요 :)'),
                            
      array('id'=>'hwangyunjung',
              'name'=>'면 상',
              'who'=>'황윤정',
              'permalink'=> 'https://www.facebook.com/hwangyunjung',
              'thumbnail'=>'https://graph.facebook.com/hwangyunjung/picture',
              'description'=>'아쉽게도 딱! 한 차례만 만화모임을 진행하셨지만 오래 기억될 만큼 의외이자 신선한 모임을 진행해 주셨어요. 그때 너구리였던걸로 기억하는데.. 라면을 끊여 먹었고요. 이후 "집밥프로젝트"의 "파스타" 부분에서 요리사역을 해주셨어요. 재밌게도 두번 다 면요리를 해주셨으니 이 상을 드리기에 안성맞춤이네요'),
                            
      array('id'=>'sookwi.cho',
              'name'=>'종합병원 앞 편의점 상',
              'who'=>'모리',
              'permalink'=> 'https://www.facebook.com/sookwi.cho',
              'thumbnail'=>'https://graph.facebook.com/sookwi.cho/picture',
              'description'=>'무슨 이름으로 드릴까 고민했는데 이 느낌의 상 이름이 좋을 것 같았어요. 보통은 안그러셔도 되는데 오실때마다 선물을 매번 사가지고 오시는데 대부분 "과일"을 사오셨어요. 그럴듯한 바구니에 담겨져 있지는 않지만 과일을 받을때마다 입원한 환자가 된 느낌도 사알~짝 :)'),
                            
      array('id'=>'choasin',
              'name'=>'지리 상',
              'who'=>'조아신',
              'permalink'=> 'https://www.facebook.com/choasin',
              'thumbnail'=>'https://graph.facebook.com/choasin/picture',
              'description'=>'멀리 지리산에서 아주 가끔 오셨지만, 집이신 지리산에 가셔서도 선물을 보내주셨던 고마운 손님이에요. "아마도"의 최초의 숙박고객이자 예전엔 자주 같이 숙박(?)했던 사이네요. 멀어서 자주 보긴 힘들지만.. 뭐 그러지 않아도 편한 느낌은 여전한 것 같네요.'),
                            
      array('id'=>'100002928455887',
              'name'=>'일단은 밥 상',
              'who'=>'키튼',
              'permalink'=> 'https://www.facebook.com/100002928455887',
              'thumbnail'=>'https://graph.facebook.com/100002928455887/picture',
              'description'=>'딱 유일한 1명이 이 상을 받으실 수 있을 것 같아요. "삼계탕", "파스타", "전"을 먹었던 "집밥프로젝트"에 모두 함께 해주셨어요. 그냥 오셔서 잘 드시고 가시는 건데.. 이렇게 고마울 수가 :)'),
                            
      array('id'=>'petercheon',
              'name'=>'멀티 플레이 상',
              'who'=>'천휘재',
              'permalink'=> 'https://www.facebook.com/petercheon',
              'thumbnail'=>'https://graph.facebook.com/petercheon/picture',
              'description'=>'가장 다양한 이유(?)로 "아마도"에서 함께 해주셔서 이 상을 드려요. 공연도 해주시고, 요리도 해주시고, 또 다른 분의 공연도 보러 오시고, 그냥 놀러도 오시고요. 특히 공연도 해주시고 요리도 해주신 "아마도 비빔밥 연주회"는 오래 기억될 좋은 이벤트였어요. 고마워요.'),
     
     array('id'=>'duhyun.ko.9',
              'name'=>'설레임 상',
              'who'=>'고두현',
              'permalink'=> 'https://www.facebook.com/duhyun.ko.9',
              'thumbnail'=>'https://graph.facebook.com/duhyun.ko.9/picture',
              'description'=>'친구가 아닌데도 예약해주시고, 찾아와주신 첫번째 손님이세요. 그때의 설레임은 아직도 기억나요. 내 집인데 어찌나 서먹서먹하고 안절부절했던지.. 그때는 그 마음이 혹시 전해질까 걱정이었죠. "아마도"의 시작을 함께해주셔서 고마워요.'),
                                          
      array('id'=>'siwawithsiwa',
              'name'=>'집 상',
              'who'=>'시와',
              'permalink'=> 'https://www.facebook.com/siwawithsiwa',
              'thumbnail'=>'https://graph.facebook.com/siwawithsiwa/picture',
              'description'=>'"아마도"에서 언젠가는 꼭 해보고 싶던 누군가의 "생일 잔치"를 해주셨던 분이세요. 게다가 공연을 해주시기도 했죠. 이름을 "집 상"이라 하게된 이유는 집에서 친구들을 초대해 생일 잔치를 하는 것 만큼 편하게 "아마도"를 집처럼 이용해 주셨기 떄문이요. 생일선물 받으실때의 그 미소를 아직도 기억해요 :)'),
                            
      array('id'=>'100002048763556',
              'name'=>'친근 상',
              'who'=>'강아솔',
              'permalink'=> 'https://www.facebook.com/100002048763556',
              'thumbnail'=>'https://graph.facebook.com/100002048763556/picture',
              'description'=>'우연히 노래를 들었다가 이후엔 참 자주 들었던 어느 노래의 주인공이 "아마도"가 있는 성북동에 가까운 곳에 살고 있다는 이야기를 들은건 참 행운이었어요. 트위터를 통한 공연 요청에 선뜻 응해주었고 역시나 좋은 공연을 해주셨죠. 처음 보자마자 참 친근하게 느꼈던 것은 남들보다 더 발달한(?) 그 분의 친화력때문만은 아닐거에요.'),
                            
      array('id'=>'peter.sinclair.902',
              'name'=>'어쩌다 상',
              'who'=>'피터',
              'permalink'=> 'https://www.facebook.com/peter.sinclair.902',
              'thumbnail'=>'https://graph.facebook.com/peter.sinclair.902/picture',
              'description'=>'지인의 꼬임(?)에 넘어가 정말 우연히 "아마도"에 방문해주셨다가 공연을 진행하게 되었어요. 가장 많은 뮤지션과 가장 많은 악기가 함께 했던 "아마도 작은 음악회"는 오래 기억될 거에요. 보통은 뮤지션분들이 오시면 "식사"를 대접하는데 너무 많이 오셔서 "샌드위치"를 준비했다가 반응이 별로 안좋아.. 너무 죄송했던 기억이 있네요 ㅜ.ㅠ'),
                            
      array('id'=>'100004098977432',
              'name'=>'산타클로스 상',
              'who'=>'견과류',
              'permalink'=> 'https://www.facebook.com/100004098977432',
              'thumbnail'=>'https://graph.facebook.com/100004098977432/picture',
              'description'=>'공연을 해주셨던 자매팀의 언니분이세요. "아마도" 공연을 위해 "신곡"을 준비해 오셨고, 선물을 준비해오셔서 제비뽑기로 선물을 나누어 주셨죠. 그래서 산타클로스 상이에요. 가장 많은 노력(?) 혹은 준비를 해주셨던 것 같아요. 그래서 더 기억에 남을 것 같아요.'),
                            
      array('id'=>'ohyujincom',
              'name'=>'산타클로스 상',
              'who'=>'오유진',
              'permalink'=> 'https://www.facebook.com/ohyujincom',
              'thumbnail'=>'https://graph.facebook.com/ohyujincom/picture',
              'description'=>'공연을 해주셨던 자매팀의 동생분이세요. "아마도" 공연을 위해 "신곡"을 준비해 오셨고, 선물을 준비해오셔서 제비뽑기로 선물을 나누어 주셨죠. 그래서 산타클로스 상이에요. 가장 많은 노력(?) 혹은 준비를 해주셨던 것 같아요. 그래서 더 기억에 남을 것 같아요.'),
      
      array('id'=>'nanshil.kwon',
              'name'=>'재활용 상',
              'who'=>'권난실',
              'permalink'=> 'https://www.facebook.com/nanshil.kwon',
              'thumbnail'=>'https://graph.facebook.com/nanshil.kwon/picture',
              'description'=>'집들이때 받으셨다던 휴지세트(티슈,키친타올,두루마리 휴지)라던가, 샀는데 안쓴다던 에그타이머, 향초세트등 집에서 사용하던 다양한 생필품을 나누어 주셨어요. 이게 바로 재활용이죠. 그래서 재활용 상을 드려요. 앞으로도 남는 것들 잘~ 부탁드려요. 하하.'),
                                   
      array('id'=>'jennifer.kang.12',
              'name'=>'떼 상',
              'who'=>'제니퍼',
              'permalink'=> 'https://www.facebook.com/jennifer.kang.12',
              'thumbnail'=>'https://graph.facebook.com/jennifer.kang.12/picture',
              'description'=>'항상 오실때마다 소수의 인원이 아니라 참~ 많은 인원들을 데리고 오세요. 올때마다 북적 북적. 나쁘지 않아요 :) 특히 6월에 열었던 "아마도 이건 작은 잔치"때 사회를 봐주신 것을 아직도 기억해요. 고마웠어요.'),
                                     
      array('id'=>'gelda2you',
              'name'=>'아마도 사진 상',
              'who'=>'조슬기',
              'permalink'=> 'https://www.facebook.com/gelda2you',
              'thumbnail'=>'https://graph.facebook.com/gelda2you/picture',
              'description'=>'늦게 알게된 손님이지만 가까운 동네주민으로서 자주 놀러와주시는 손님이세요. 아마 가장 빠른 시간내에 가장 많이 오신 손님이 아니실지.. 좋은 스티커 활용사진도 올려주시고 운영하시는 홈페이지에도 스티커가 붙어있었어요.'),
                            
      array('id'=>'zoni.cho',
              'name'=>'아마도 사진 상',
              'who'=>'조니',
              'permalink'=> 'https://www.facebook.com/zoni.cho',
              'thumbnail'=>'https://graph.facebook.com/zoni.cho/picture',
              'description'=>'"아마도"가 있는 성북동에서 가까운 삼선동에 위치한 베이킹 스튜디오를 운영하고 계시는 사장님(?)이세요. "아마도"라고 하시며 만들어주신 집 모양의 쿠키에 "아마도 스티커"를 붙여서 출품해주셨어요. 그래서 수상하셨어요 :)'),
                            
      array('id'=>'100000997647836',
              'name'=>'아마도 사진 상',
              'who'=>'김지은',
              'permalink'=> 'https://www.facebook.com/100000997647836',
              'thumbnail'=>'https://graph.facebook.com/100000997647836/picture',
              'description'=>'지리산 손님을 제외하면 가장 멀리서 찾아와 주신 손님이 아닐까 하네요. 강원도에서 보내주신 여러장의 "아마도 스티커"활용 사진은 충분히 수상하실 만 하셨어요. 특히 시골(?)에서 가져온 "호박"이라던가 "감자"를 올때마다 조금씩 가져와 주셔서 너무 고마웠어요. (사실 좋아하는 야채는 아니지만요 하하)'),
                            
      array('id'=>'100002272722422',
              'name'=>'아마도 사진 상',
              'who'=>'장은지',
              'permalink'=> 'https://www.facebook.com/100002272722422',
              'thumbnail'=>'https://graph.facebook.com/100002272722422/picture',
              'description'=>'아마도 수상자분들 중 가장 나중에 "아마도"를 찾아와 주신 분이지 않을까 하네요. 운이 좋으세요 :) 12월엔 여러번 함께 "아마도"에서 작은 이벤트들을 열 것 같아... 자주 보게될 분 같아요. 제주에서 공수해 온 녹차씨앗을 선물로 주셔서 어떻게 해야하나 난감해 하고 있어요. 하하. 내년 봄에 도전해볼까 해요.'),
                            
      array('id'=>'shout.louder',
              'name'=>'아마도 사진 상',
              'who'=>'이건임',
              'permalink'=> 'https://www.facebook.com/shout.louder',
              'thumbnail'=>'https://graph.facebook.com/shout.louder/picture',
              'description'=>'"아마도상" 수상자중 가장 가까운 곳에 살고 계시는 분이 아닐까 하네요. "아마도 약통"이라는 이름으로 약통에 스티커를 붙여 주신 사진을 올려주셨어요 :) 얼마 전 선물해주신 "아마도 향초"도 매우 유용하게 사용하고 있어요. 고마워요.'),
                            
      array('id'=>'bono.kong',
              'name'=>'특별 상',
              'who'=>'공',
              'permalink'=> 'https://www.facebook.com/bono.kong',
              'thumbnail'=>'https://graph.facebook.com/bono.kong/picture',
              'description'=>'"아마도상"을 위해 그림을 준비하셨다는 말에.. 아직 받지 못했지만 혹시나 하는 마음에 이 상을 드려요. 정말 정말 받고 싶은 그림 선물이라 특별히 사심을 담아 이 특별 상을 드려요. 기대해도 되죠? :)')
              
    );